dist: xenial
language: python
python:
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
#install:
#  - 'pip install pipenv'
#  - 'pipenv --dev install'
# command to run tests
script:
  - make install travis_test