dist: xenial
language: python
python:
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
  - cp config.py.dist config.py
# command to run tests
script:
  - make install travis_test